[DB_SRC_User]
	dialect = "mysql"   # DB类型:mysql
	#dsn = "root:123456@tcp(127.0.0.1:3306)/deepin_user_de?parseTime=true&loc=Local&charset=utf8mb4,utf8"      # 地址 --UserDE
	#dsn = "root:123456@tcp(127.0.0.1:3306)/deepin_user?parseTime=true&loc=Local&charset=utf8mb4,utf8"      # 地址 --UserCN
	dsn = "root:123456@tcp(127.0.0.1:3306)/src_pre_deepin_user?parseTime=true&loc=Local&charset=utf8mb4,utf8"      # 地址 --pre测试
	maxOpenConns = 100                      # 最大连接数
	maxIdleConns = 50                       # 最大空闲连接数
	connMaxLifetime = 300                   # 最大空闲回收时间，单位：s
	logMode = true                          # 是否开启debug日志
	logSQL =true                            # 是否显示sql中具体值
	slowThreshold = 500                     # 慢日志阈值，单位：ms

[DB_SRC_Oauth]
	dialect = "mysql"   # DB类型:mysql
	dsn = "root:123456@tcp(127.0.0.1:3306)/deepinid?parseTime=true&loc=Local&charset=utf8mb4,utf8"      # 地址
	#dsn = "root:123456@tcp(127.0.0.1:3306)/src_pre_deepinid?parseTime=true&loc=Local&charset=utf8mb4,utf8"      # 地址 --pre测试
	maxOpenConns = 100                      # 最大连接数
	maxIdleConns = 50                       # 最大空闲连接数
	connMaxLifetime = 300                   # 最大空闲回收时间，单位：s
	logMode = false                          # 是否开启debug日志
	logSQL =true                            # 是否显示sql中具体值
	slowThreshold = 500                     # 慢日志阈值，单位：ms

[DB_DST_User]
	dialect = "mysql"   # DB类型:mysql
	dsn = "deepinid_user:deepinid_user@tcp(mariadb-master-test.sndu.cn:3306)/deepinid_user?parseTime=true&loc=Local&charset=utf8mb4,utf8"      # 地址
	#dsn = "root:123456@tcp(127.0.0.1:3306)/test_deepinid_user?parseTime=true&loc=Local&charset=utf8mb4,utf8"      # 地址
	maxOpenConns = 100                      # 最大连接数
	maxIdleConns = 50                       # 最大空闲连接数
	connMaxLifetime = 300                   # 最大空闲回收时间，单位：s
	logMode = false                          # 是否开启debug日志
	logSQL =true                            # 是否显示sql中具体值
	slowThreshold = 500                     # 慢日志阈值，单位：ms

[DB_DST_Oauth]
	dialect = "mysql"   # DB类型:mysql
	#dsn = "deepinid:deepinid@tcp(mariadb-master-test.sndu.cn:3306)/deepinid?parseTime=true&loc=Local&charset=utf8mb4,utf8"      # 地址
	dsn = "root:123456@tcp(127.0.0.1:3306)/test_deepinid?parseTime=true&loc=Local&charset=utf8mb4,utf8"      # 地址
	maxOpenConns = 100                      # 最大连接数
	maxIdleConns = 50                       # 最大空闲连接数
	connMaxLifetime = 300                   # 最大空闲回收时间，单位：s
	logMode = false                          # 是否开启debug日志
	logSQL =true                            # 是否显示sql中具体值
	slowThreshold = 500                     # 慢日志阈值，单位：ms

[Log]
	#output = "file"
	output = "stdout"
	level = "info"
	jsonEncode = true
	dir = "./logs"
	fileName = "test.log"
	addCaller = true
	callerSkip = 2
	maxSize = 128
	maxAge = 30
	maxBackups = 7
	compress = true
	[Log.fields]
		appName = "dataMigrate"